### ISSUE TITLE
Baseline experiments mentioned in OpenReview

### ISSUE THREAD

**Issue by mch5048** [YuLiu-LY/BO-QSA#4]
Hi, thanks for sharing insightful work on improving and understanding the potential of SlotAttention.

I have read through the discussions in the OpenReview and gotten more insights regarding the paper.
I want to understand more by reading through the codes of the additional experiments conducted and mentioned in OpenReview.

[Here,](https://openreview.net/forum?id=_-FN9mJsgg&noteId=AoUaKYQ3Pn) an extensive study for post-clustering methods are conducted and I am wonder how the baselines could be implemented (or if it is already implemented in this repo, could you give pointers to it?).

Thanks in advance!

**Comment by YuLiu-LY** [comment]
We did not add the implementation of post-clustering because of its bad performance. We added it just now. You can experiment with configs:
`
--use_post_cluster \ 
--use_kmeans \
--lambda_c 0.1 \
`
In our implementation, we consider 2 ways of clustering and 2 ways of updating clusters. 
Clustering: 
    Given a batch of images, we 
    1. directly use the mean of the batch of final slots after slot attention as the post clusters, then use the clusters as slots_init of the next batch.
    2. do K-means on the final slots, and update the post cluster with the results of K-means.
Updating:
    Given clusters, we
     1. directly update clusters. `self.cluster = new_cluster`
     2. adopt momentum update. `self.cluster = lambda * new_cluster + (1 - lambda) * self.cluster`
You can read our code for details now.
Hope this can help you.

**Comment by mch5048** [comment]
Thanks for the quick response and generous code sharing! It would be a great help.
